---
# Available languages: eng, deu
lang: "eng"

# Available providers: yaml
provider: "yaml"

# How many plots a player can own
max-plots: 2

# Determine if you should be teleported to the plot border when the plot is claimed
teleport-on-claim: true

# Whether the popup should appear when you enter a plot
show-popup: true

# Here you find the plot configurations,
# how the plot world should look like later, when the world is generated for the first time
default-settings:
  plotSize: 32
  roadBlock: 5
  wallBlock: 44
  bottomBlock: 7
  plotFloorBlock: 2
  plotFillBlock: 3
  roadWidth: 7
  groundHeight: 64
...