---
# Do not change the version, this can lead to deletion of the file
version: "1.3.1"

# Available languages:
# eng (English), deu (German), kor (Korean), chs (Chinese)
lang: "eng"

# Allow tracking statistics on how the plugin is used
metrics: true

# Available providers: yaml, mysql, sqlite
# Default: yaml
provider: "yaml"

# Automatic saving of all plots
# Supported providers: yaml
auto-save:
  use: true
  # In seconds
  interval: 180

# NOT COMPLETED!
# Should the XUID be used to keep the plot when changing the player name
# xuid: false

# MySQL connection data
mysql:
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "ThisIsMyStrongPassword"
  database: "futureplots"

# To be able to locate an error correction more precisely
debug: false

# How many plots a player can own
max-plots: 2

# Determine if you should be teleported to the plot border when the plot is claimed
teleport-on-claim: true

# Whether the popup should appear when you enter a plot
show-popup: true

# Decide here whether Economy should be used for claiming, emptying and deleting plots
# Provider: EconomyAPI, LlamaEconomy
# If you want to use Economy, set this to true. FuturePlots will automatically search for an available provider if the plugin is on the server.
economy:
  enable: false
  # To use Economy in worlds, specify below the worlds in which Economy should be enabled, as in the example.
  # Example:
  # worlds:
  #  - "plotworld"
  #  - "citybuild"
  worlds: []

# Before an interaction can be executed, it must be confirmed again.
confirmations: true

# Decide if you want to use UIs for plot interactions.
forms: false

# Here you find the plot configurations,
# how the plot world should look like later, when the world is generated for the first time
default-settings:
  plotSize: 32
  roadBlock: "5:0"
  wall:
    unclaimed: "44:0"
    claimed: "44:1"
  bottomBlock: "7:0"
  plotFloorBlock: "2:0"
  plotFillBlock: "3:0"
  roadWidth: 7
  groundHeight: 64
  price:
    claim: 500
    clear: 300
    delete: 200
    dispose: 500
    erode: 500
    merge: 1000
...
